plugins:
  composer_help_button_enabled:
    default: true
    client: true
  composer_help_button_url:
    default: ""
    client: true
  composer_help_button_label:
    default: "Help"
    client: true
  composer_help_button_title:
    default: "Composer Help"
    client: true
